version: "3"

services:
  bff:
    build: .
    container_name: borneappetit_bff
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_URL=http://gateway:9500
    networks:
      - restaurant-nestjs_nestjs-restaurant-network
    depends_on:
      - orders_database

  orders_database:
    image: postgres:latest
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - orders_database:/data/db
    networks:
      - restaurant-nestjs_nestjs-restaurant-network

volumes:
  orders_database:

networks:
  restaurant-nestjs_nestjs-restaurant-network:
      external: true
