version: "3"

services:
  bff:
    build: .
    container_name: borneappetit_bff
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_URL=http://gateway:3000
    networks:
      - restaurant-nestjs_nestjs-restaurant-network

networks:
  restaurant-nestjs_nestjs-restaurant-network:
      external: true
