version: "3"

services:
  bff:
    build: .
    container_name: borneappetit_bff
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_URL=http://localhost:9500 # todo: resolve the gateway_url
    volumes:
      - .:/usr/src/app
