version: "3"

services:
  bff:
    build: .
    container_name: borneappetit_bff
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_URL=http://gateway:8080
    networks:
      - restaurant_spring-restaurant-network

networks:
  restaurant_spring-restaurant-network:
      external: true
